# Generated by Django 4.2.7 on 2023-11-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_exchangeorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeorder',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='exchangeorder',
            name='cryptocurrency_type',
        ),
        migrations.RemoveField(
            model_name='exchangeorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='exchangeorder',
            name='wallet_address',
        ),
        migrations.AddField(
            model_name='exchangeorder',
            name='crypto_from',
            field=models.CharField(default='BTC', max_length=255),
        ),
        migrations.AddField(
            model_name='exchangeorder',
            name='crypto_to',
            field=models.CharField(default='USDT', max_length=255),
        ),
        migrations.AddField(
            model_name='exchangeorder',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangeorder',
            name='usdt_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
