# Generated by Django 4.2.7 on 2023-11-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_remove_exchangeorder_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='exchangeorder',
            name='crypto_from',
            field=models.CharField(choices=[('ETH', 'eth'), ('XMR', 'xmr'), ('DAI', 'dai'), ('DASH', 'dash'), ('Dogecoin', 'dogecoin')], default='BTC', max_length=255),
        ),
        migrations.AlterField(
            model_name='exchangeorder',
            name='crypto_to',
            field=models.CharField(choices=[('ETH', 'eth'), ('XMR', 'xmr'), ('DAI', 'dai'), ('DASH', 'dash'), ('Dogecoin', 'dogecoin')], default='USDT', max_length=255),
        ),
    ]
