# Generated by Django 4.2.7 on 2023-11-07 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_exchangeorder_amount_alter_exchangeorder_crypto_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeorder',
            name='usdt_address',
        ),
    ]
