# Generated by Django 4.2.7 on 2023-11-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_remove_exchangeorder_usdt_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeorder',
            name='recipient_wallet',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
