# Generated by Django 4.2.7 on 2023-11-08 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_exchangeorder_recipient_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeorder',
            name='recipient_wallet',
        ),
    ]
