# Generated by Django 4.2.7 on 2023-11-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_exchangeorder_crypto_walet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('crypto_from', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recipient_wallet', models.CharField(max_length=255)),
                ('crypto_to', models.CharField(max_length=255)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='ExchangeOrder',
        ),
    ]
