# Generated by Django 4.2.7 on 2023-11-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0011_order_delete_exchangeorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='crypto_from',
            field=models.CharField(choices=[('ETH', 'eth'), ('XMR', 'xmr'), ('DAI', 'dai'), ('DASH', 'dash'), ('Dogecoin', 'dogecoin')], max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='crypto_to',
            field=models.CharField(choices=[('ETH', 'eth'), ('XMR', 'xmr'), ('DAI', 'dai'), ('DASH', 'dash'), ('Dogecoin', 'dogecoin')], max_length=255),
        ),
    ]
