# Generated by Django 4.2.7 on 2023-11-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0014_order_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='you_get',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
